### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by tabowling** [fulup-bzh/AlsaJsonGateway#12]
Hello.  I am having a number of issues attempting to install this and getting it to work properly with Alsa Json Mixer.

I am using Fedora 28.  All dependencies install fine and compiles complete without error.  Only problems with installing and actually getting it to work.  I think a simple step by step, copy commands from readme file would be more helpful than the video.

1. The instructions say export AJW_DIR=$HOME/AJW.  However, should this be /opt/ajg-daemon instead?
2. sudo make install does not create /opt/ajg-daemon directory.  Even if I manually create it, nothing is installed there.  Instead, there are files installed into /usr/local/var/www/fakemod.  I cannot see that any other files are installed anywhere else.

Please provide some guidance, I am very interested in the excellent work you have done and using my Scarlett 6i6!

**Comment by tabowling** [comment]
I made some progress by ignoring the previous AJW_DIR and instead using my local dir.

export ROOTDIR=$HOME/.ajg/www
export CONFIG=$HOME/.ajg/default.conf
export SESSIONDIR=$HOME/.ajg/sessions

ajg-daemon --saveonly --sessiondir=$SESSIONDIR --rootdir=$ROOTDIR --config=$CONFIG
ajg-daemon --verbose --config=$CONFIG

This now somewhat works in that it detects both my internal sound card and Focusrite Scarlett 6i6 USB.

However, when I select the 6i6, it complains that there are no sessions and I can't really do anything.  If click the refresh sessions arrow button, it complains that there are no sessions in my $HOME.ajg/sessions/.  It does now show any of the hardware abilities, just an empty shell.

**Comment by fulup-bzh** [comment]
The session should not be an issue, if you have one then you might restore it, otherwise you cannot. The only thing is that alsajsongateway should be able to create a file in $HOME.ajg/sessions.

Note that I never did any test with the 6i6 and even it I try to make the code generic I may have an error in the HTML5 UI part when processing sound card control name.

**Comment by wwp** [comment]
The "Starting alsa-json-gateway" in the README.md file is confusing. It's missing several $ to address variable names, IOW the maintainer didn't test the doc to see if the mentioned commands do work or not. More over, it's not clear if we have to chain all those commands to start the gateway? Or is this a set of possible commands? More over, what can or must be started at root?

By following the commands described on top of this thread, I end up with:
```
AJG:notice checking session dir [/root/.ajg/sessions]
AJG: Fail to chdir to /root/.ajg/sessions error=Unknown error -1

ERR:cannot read/write session dir

```
Manually creating /root/.ajg/sessions  doesn't help.
Any hint?

**Comment by fulup-bzh** [comment]
You're right for documentation probably a bad cut&paste.

- You should not run it as root if you check the error message you will see that when started as as root, the daemon shift privilege to nobody.
- Retry with a standard user and it will work.
- Last option if you MUST run as root, give /root/.ajg/sessions to nobody or choose 777 as access right.
