### ISSUE TITLE
make a release for xenial in PPA

### ISSUE THREAD

**Issue by wolftune** [fulup-bzh/AlsaJsonGateway#6]
The PPA isn't usable for newer systems 16.04 or 16.10 because there's been no release published. Please publish one so the PPA is usable. Thanks

**Comment by fulup-bzh** [comment]
Unfortunately I do not have time to maintain binary distribution. On the other hand recompiling AlsaJsonGatreway is really simple.

On the other hand if you willing to update the PPA, you're welcome.

Sorry for that.
