### ISSUE TITLE
issue with make 

### ISSUE THREAD

**Issue by disasterman573** [fulup-bzh/AlsaJsonGateway#9]
Hello and thanks for the work you do on this!  I am getting an error in attempting to make the the file. Please see the following:  

In function ‘strncat’,
    inlined from ‘alsaFakeResponse.isra.0’ at alsa-ajg.c:60:12:
/usr/include/x86_64-linux-gnu/bits/string3.h:156:10: error: call to __builtin___strncat_chk might overflow destination buffer [-Werror]
   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));

**Comment by fulup-bzh** [comment]
Thank you or your comment. What you describe is only a warning in the fake mode and the the priority to fix this remains weak.

You might also be interested to known that I'm currently working on https://github.com/iotbzh/audio-bindings while this project is not finish yet, it already does more than AlsaJsonGateway. If you're interested in using AlsaJsonGateway for a project I would recomment to switch to audio-bindings that is far more advanced.
